### ISSUE TITLE
Questions about display a category of one image

### ISSUE THREAD

**Issue by achel-x** [hysts/pytorch_D-RISE#1]
Thank you for sharing. I am interesting about this work. While I use the YOLOv3 https://github.com/ultralytics/yolov3/  as the object detector. 
I can generate the salience map when the image only have one object with a category, like the followings.
![image](https://user-images.githubusercontent.com/67953243/152715341-78ccd3a1-0bcc-4896-881f-4420dda7f488.png)

While it can't work when the image contain multiple objects of a categories like the persons in this image
![image](https://user-images.githubusercontent.com/67953243/152715873-2907c588-3ebb-498c-9274-17b270c9d3fe.png)

The code compute the score I revised it as 
'conf = max([iou(target_box, box)*conf], default=0)'

Could you give me some advice?

**Comment by RuoyuChen10** [comment]
> Thank you for sharing. I am interesting about this work. While I use the YOLOv3 https://github.com/ultralytics/yolov3/ as the object detector. I can generate the salience map when the image only have one object with a category, like the followings. ![image](https://user-images.githubusercontent.com/67953243/152715341-78ccd3a1-0bcc-4896-881f-4420dda7f488.png)
> 
> While it can't work when the image contain multiple objects of a categories like the persons in this image ![image](https://user-images.githubusercontent.com/67953243/152715873-2907c588-3ebb-498c-9274-17b270c9d3fe.png)
> 
> The code compute the score I revised it as 'conf = max([iou(target_box, box)*conf], default=0)'
> 
> Could you give me some advice?

I applied on Yolo v3 and don't appear the problem you said.

**Comment by achel-x** [comment]
@RuoyuChen10 could you share your code with me? My email is achel_x@163.com.

**Comment by RuoyuChen10** [comment]
> @RuoyuChen10 could you share your code with me? My email is [achel_x@163.com](mailto:achel_x@163.com).

sure, I will send it to you soon, and I will also upload it to my GitHub in the future: [https://github.com/RuoyuChen10/objectdetection-saliency-maps](https://github.com/RuoyuChen10/objectdetection-saliency-maps)

**Comment by hysts** [comment]
Sorry I missed this issue. Looks like it's already been solved, so I'll close this.
